try:
    import framebuf
except ImportError:
    from . import framebuf

class SSD1306_Emu(framebuf.FrameBuffer):
    width: int
    height: int
    def __init__(self, width: int, height: int, *args, main_process = ..., **kws) -> None: ...
    def poweroff(self) -> None: ...
    def poweron(self) -> None: ...
    def contrast(self, contrast: int) -> None: ...
    def invert(self, invert: bool) -> None: ...
    def show(self) -> None: ...
    def refresh(self, x: int, y: int, w: int, h: int) -> None: ...
    def pygame_loop(self, wait=...) -> None: ...
